# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
np.shape(a)

(10,)

5. Print the type of the previous array in question 3

In [5]:
print(b.dtype)

int32


6. Print the numpy version and the configuration

In [6]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']

7. Print the dimension of the array in question 3


In [7]:
print(b.ndim)

1


8. Create a boolean array with all the True values

In [8]:
c = np.ones((3, 3), dtype = bool)
c

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array




In [9]:
d = np.arange(1, 11)
d.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

10. Create a three dimensional array



In [10]:
e = np.random.rand(3,3,3)
e

array([[[0.65531833, 0.54813184, 0.27645002],
        [0.39645628, 0.84905011, 0.58418661],
        [0.43977167, 0.48255728, 0.99340119]],

       [[0.88806481, 0.15204175, 0.19188848],
        [0.65421975, 0.32535828, 0.84395971],
        [0.98275099, 0.28143186, 0.82489798]],

       [[0.69496831, 0.02582171, 0.32258452],
        [0.24412763, 0.89129387, 0.63536362],
        [0.00543316, 0.55825102, 0.50866248]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
reverse_array = e[::-1]
reverse_array

array([[[0.69496831, 0.02582171, 0.32258452],
        [0.24412763, 0.89129387, 0.63536362],
        [0.00543316, 0.55825102, 0.50866248]],

       [[0.88806481, 0.15204175, 0.19188848],
        [0.65421975, 0.32535828, 0.84395971],
        [0.98275099, 0.28143186, 0.82489798]],

       [[0.65531833, 0.54813184, 0.27645002],
        [0.39645628, 0.84905011, 0.58418661],
        [0.43977167, 0.48255728, 0.99340119]]])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
f = np.arange(1,11)
f[4] = (1)
f

array([ 1,  2,  3,  4,  1,  6,  7,  8,  9, 10])

13. Create a 3x3 identity matrix

In [13]:
g = np.identity(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(float)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr3 = arr1 == arr2
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
odd_numbers = (arr % 2 == 1)
odd_numbers

array([ True, False,  True, False,  True])

18. Replace all odd numbers to -1 from previous array

In [18]:
arr[odd_numbers] = -1
arr

array([-1.,  2., -1.,  4., -1.])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9] = [12]
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
d_array = np.ones((3,3))
d_array
d_array[1,1] = 0
d_array

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
h = np.arange(0,9).reshape(3,3,-1)
h[0]

array([[0],
       [1],
       [2]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
l = np.arange(0,9).reshape(3,3,-1)
l[1,1]

array([4])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
m = np.arange(0,9).reshape(3,3,-1)
m[2,:2]

array([[6],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
n = np.random.rand(10,10)
n.min()
n.max()

0.9922827500020933

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
o = np.intersect1d(a, b)
o

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
p = (a == b)
p

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
q = (names != names[4])
q

array([ True,  True, False,  True, False,  True,  True])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
q = (names != names[4],[5])
q

(array([ True,  True, False,  True, False,  True,  True]), [5])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
r = np.arange(15).reshape(5,3)
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
s = np.arange(16).reshape(2,2,4)
s

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

33. Swap axes of the array you created in Question 32

In [33]:
np.swapaxes(s,0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
t = np.random.rand(10)
np.sqrt(t)
t[t < 0.5] = 0
t

array([0.        , 0.94959829, 0.        , 0.        , 0.        ,
       0.        , 0.61139717, 0.        , 0.        , 0.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [75]:
u = np.random.rand(12)
v = np.random.rand(12)
print(u)
print(v)
np.maximum(u, v)

[0.00985015 0.41743754 0.02901703 0.38495442 0.73308608 0.17190915
 0.22793081 0.3009415  0.15480758 0.31531371 0.97353228 0.60028181]
[0.25988464 0.29558704 0.96418901 0.58611191 0.1973848  0.79657495
 0.8745265  0.94663583 0.6135211  0.33061083 0.39187748 0.93238749]


array([0.25988464, 0.41743754, 0.96418901, 0.58611191, 0.73308608,
       0.79657495, 0.8745265 , 0.94663583, 0.6135211 , 0.33061083,
       0.97353228, 0.93238749])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names = np.unique(names)
np.sort(unique_names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [74]:
a = np.array([1,2,3,4,5])
print(a)
b = np.array([5,6,7,8,9])
print(b)
removed_b = np.setdiff1d(a, b)
print(removed_b)

[1 2 3 4 5]
[5 6 7 8 9]
[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [71]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)
arr = np.array([[10,10,10]])
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [73]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [84]:
random_matrix1 = np.random.rand(20)
print(random_matrix1)
random_matrix2 = np.random.rand(20)
print(random_matrix2)
a = (random_matrix1, random_matrix2)
np.cumsum(a)

[0.24963953 0.65138343 0.58843571 0.09914614 0.35679906 0.15400069
 0.42419338 0.09665261 0.27390457 0.99278396 0.36636397 0.76900229
 0.31534051 0.33711736 0.31339506 0.95793676 0.44728626 0.08826951
 0.55166568 0.65933624]
[0.00474635 0.11984722 0.63717861 0.68970675 0.27738341 0.48875162
 0.59900369 0.97161121 0.11372257 0.45030468 0.60400466 0.91976243
 0.11282793 0.19334121 0.1227347  0.79585686 0.4656239  0.66319543
 0.85544919 0.45828728]


array([ 0.24963953,  0.90102296,  1.48945868,  1.58860481,  1.94540388,
        2.09940457,  2.52359795,  2.62025056,  2.89415513,  3.88693908,
        4.25330305,  5.02230534,  5.33764585,  5.67476322,  5.98815827,
        6.94609504,  7.3933813 ,  7.4816508 ,  8.03331648,  8.69265272,
        8.69739907,  8.8172463 ,  9.45442491, 10.14413166, 10.42151507,
       10.91026668, 11.50927037, 12.48088158, 12.59460416, 13.04490884,
       13.64891349, 14.56867592, 14.68150385, 14.87484506, 14.99757977,
       15.79343662, 16.25906052, 16.92225595, 17.77770514, 18.23599242])